"""rename material title to file name

Revision ID: 8199429ec21a
Revises: a3acf2f0cd96
Create Date: 2026-08-23 13:14:01.963192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8199429ec21a'
down_revision = 'a3acf2f0cd96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_material_lesson_file_name', ['lesson_id', 'file_name'])
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=150), nullable=False))
        batch_op.drop_constraint('uq_material_lesson_file_name', type_='unique')

    # ### end Alembic commands ###
