"""cascade delete lesson progress

Revision ID: ad0d08a7be75
Revises: 8199429ec21a
Create Date: 2026-08-23 19:27:01.372351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0d08a7be75'
down_revision = '8199429ec21a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('lesson_progress_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('lesson_progress_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'enrollments', ['enrollment_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lesson_progress_ibfk_1'), 'enrollments', ['enrollment_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('lesson_progress_ibfk_2'), 'lessons', ['lesson_id'], ['id'])

    # ### end Alembic commands ###
